### ISSUE TITLE
Icons not loading in Release mode

### ISSUE THREAD

**Issue by ivanrlg** [jamesmontemagno/app-peloton#1]
Hi,

First of all, congratulations and thank you for your great work and work to do in the world of software, you have been a great guide for learning Xamarin.

I have used the way you implement the icons of this app in mine, everything works fine in debug mode, unlike your app, I have additionally created the app in UWP and published it in the Microsoft Store. So when the app is downloaded I see that the icons all look like little rectangles. (As if it didn't recognize the font, which I additionally installed on the local machine.) Do you have any idea why this happens? Or what could I try to avoid it?

Regards,

**Comment by jamesmontemagno** [comment]
You have to set the Icon in the Package.appmxanifest _> https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos

**Comment by ivanrlg** [comment]
Hi James, thank you for your reply. But I am referring to the font awesome icons. Is it possible to associate them to the manifest? Thank you.

**Comment by jamesmontemagno** [comment]
Ah, on UWP you need to make sure you pass in the assembly referencing it -> https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#set-the-font-family see the "IMPORTANT" flag there.

**Comment by ivanrlg** [comment]
Hi James,

It worked. Thank you for your time.

Best regards.
